FROM golang:latest

ENV GO111MODULE=on

WORKDIR /app

COPY ./ /app

RUN go mod download

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -directory="/app" --build="go build cmd/wallet-api.go" --command="./wallet-api"